Repository Capstone-LGBTQ-BIPOC/FE_DiverCity, pull requests merged in 2022-05, with the labels that each got.

#37 Closes #7 - Feature/modal
  src/apiCalls.js
  src/components/App/App.js
  src/components/BusinessCard/BusinessCard.js
  src/components/Listings/Listings.js
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/context/BusinessData/BusinessContext.js
Labels: enhancement, Front End

#36 Closes issue#32 Feature/error handling city
  src/components/Listings/Listings.js
  src/context/BusinessData/BusinessContext.js
  src/context/LocationContext/LocationContext.js
Labels: enhancement, Front End

#38 Testing/round 1 - main page user flow
  .circleci/config.yml
  cypress.json
  cypress/fixtures/sampleEntertainmentData.json
  cypress/fixtures/sampleFoodData.json
  cypress/fixtures/sampleGeoData.json
  cypress/fixtures/sampleShoppingData.json
  cypress/integration/main_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/CategoryCard/CategoryCard.js
  src/components/Form/Form.js
Labels: Front End, testing

#43 Feature/bookmark businesses
  src/components/App/App.js
  src/components/Bookmarks/Bookmarks.css
  src/components/Bookmarks/Bookmarks.js
  src/components/BusinessCard/BusinessCard.js
  src/components/Listings/Listings.js
  src/contexts/BookmarkContext.js
Labels: Front End

#46 Feature/navigation
  src/components/App/App.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
Labels: Front End

#49 Closes #48 Refactor bookmark functionality to single business view.
  src/components/BusinessCard/BusinessCard.js
  src/contexts/BookmarkContext.js
Labels: Front End, refactor

#47 Closes #11 Testing/round 2
  cypress/fixtures/noResults.json
  cypress/fixtures/singleBiz1.json
  cypress/fixtures/singleBiz2.json
  cypress/integration/bookmark_spec.js
  cypress/integration/error_handling_spec.js
  cypress/integration/listings_spec.js
  cypress/integration/main_spec.js
  cypress/integration/navigation_spec.js
  cypress/integration/single_business_spec.js
  src/components/BusinessCard/BusinessCard.js
  src/components/Categories/Categories.js
  src/components/CategoryCard/CategoryCard.js
  src/components/Form/Form.js
  src/components/Listings/Listings.js
Labels: Front End, testing

#52 Feature/recommendations
  src/apiCalls.js
  src/components/Modal/Modal.js
Labels: enhancement, Front End

#53 Refactor/business hours
  cypress/integration/single_business_spec.js
  src/components/Modal/Modal.js
Labels: bug, Front End

#51 Refactor/location
  cypress/integration/bookmark_spec.js
  cypress/integration/error_handling_spec.js
  cypress/integration/listings_spec.js
  cypress/integration/main_spec.js
  cypress/integration/navigation_spec.js
  cypress/integration/single_business_spec.js
  src/components/BusinessCard/BusinessCard.js
  src/components/Form/Form.js
  src/components/Listings/Listings.js
  src/contexts/BusinessContext.js
  src/contexts/LocationContext.js
Labels: refactor

#54 Testing/round 3
  cypress/fixtures/noResults.json
  cypress/fixtures/sampleRecommendationData.json
  cypress/integration/bookmark_spec.js
  cypress/integration/single_business_spec.js
Labels: Front End, refactor, testing

#56 Closes Issue #55 - Refactor/prop types
  src/components/BusinessCard/BusinessCard.js
  src/components/CategoryCard/CategoryCard.js
  src/components/Listings/Listings.js
  src/components/Nav/Nav.js
Labels: Front End, refactor

#58 Styling/main
  cypress/integration/error_handling_spec.js
  cypress/integration/listings_spec.js
  cypress/integration/main_spec.js
  cypress/integration/single_business_spec.js
  public/index.html
  src/Images/header-image.jpg
  src/components/App/App.css
  src/components/App/App.js
  src/components/Categories/Categories.css
  src/components/Categories/Categories.js
  src/components/CategoryCard/CategoryCard.css
  src/components/CategoryCard/CategoryCard.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
Labels: Front End, styling

#59 Styling/single biz
  cypress/integration/single_business_spec.js
  src/components/App/App.css
  src/components/Form/Form.css
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/components/Nav/Nav.css
  src/utils.js
Labels: Front End, styling

#60 Styling/listings
  cypress/integration/listings_spec.js
  src/components/BusinessCard/BusinessCard.css
  src/components/BusinessCard/BusinessCard.js
  src/components/Listings/Listings.css
  src/components/Listings/Listings.js
Labels: Front End, styling

#64 Closes Issue #62 - Styling/bookmarks
  src/components/Bookmarks/Bookmarks.css
Labels: Front End, styling

#65 Docs/readme
  README.md
Labels: documentation, Front End

#66 Closes #63 - Refactor/listings
  src/components/Listings/Listings.js
Labels: Front End, refactor

#67 Add styling for 404 styling
  src/components/Error404/Error404.css
  src/components/Error404/Error404.js
Labels: Front End, styling

#68 Refactor/round 2
  README.md
  package-lock.json
  package.json
  src/components/Bookmarks/Bookmarks.js
  src/components/Listings/Listings.js
  src/components/Modal/Modal.js
  src/contexts/LocationContext.js
  src/index.css
Labels: Front End, refactor
